// =============================================================================
// SMS Gateway Type Definitions
// Enterprise Shopify App — SMS Adapter Pattern
// =============================================================================

// Gateway types
export type SMSGatewayType = 'SMS_MISR' | 'VICTORY_LINK' | 'WE_API';

export type SMSDeliveryStatus =
  | 'pending'
  | 'queued'
  | 'sent'
  | 'delivered'
  | 'failed'
  | 'bounced'
  | 'rejected';

export type SMSMessageEncoding = 'GSM_7BIT' | 'UCS2' | 'AUTO';

// -----------------------------------------------------------------------------
// Core interfaces
// -----------------------------------------------------------------------------

export interface SMSGatewayConfig {
  id: string;
  shopId: string;
  gatewayType: SMSGatewayType;
  /** Decrypted by manager before passing to adapter */
  username: string;
  /** Decrypted by manager before passing to adapter */
  password: string;
  apiKey?: string;
  senderName: string;
  isActive: boolean;
  /** Lower number = higher priority (tried first during failover) */
  priority: number;
  /** Request timeout in milliseconds (default 10000) */
  timeoutMs?: number;
}

export interface SMSMessagePayload {
  /** Normalized +20XXXXXXXXXX format */
  recipientPhone: string;
  message: string;
  senderName?: string;
  /** Tracking ID generated by caller or auto-generated */
  messageId?: string;
  encoding?: SMSMessageEncoding;
  /** For scheduled sends */
  scheduledAt?: Date;
}

export interface SMSMessageResponse {
  success: boolean;
  /** Gateway-returned message ID for delivery tracking */
  externalMessageId?: string;
  recipientPhone: string;
  gatewayType: SMSGatewayType;
  statusCode?: string;
  statusMessage?: string;
  cost?: number;
  currency?: string;
  latencyMs: number;
  timestamp: Date;
  /** Whether the caller should retry on a different gateway */
  retryable: boolean;
}

export interface SMSBalanceResponse {
  success: boolean;
  balance?: number;
  currency?: string;
  unit?: string; // "credits" | "currency" | "SMS"
  error?: string;
}

export interface SMSHealthCheckResult {
  gatewayType: SMSGatewayType;
  isHealthy: boolean;
  latencyMs: number;
  lastError?: string;
  checkedAt: Date;
}

export interface SMSBatchPayload extends SMSMessagePayload {
  /** Override single recipient with multiple */
  recipients: string[];
}

export interface SMSBatchResponse {
  totalRecipients: number;
  successfulCount: number;
  failedCount: number;
  results: SMSMessageResponse[];
  gatewayType: SMSGatewayType;
  totalLatencyMs: number;
}

// -----------------------------------------------------------------------------
// Events (for event bus / webhook integration)
// -----------------------------------------------------------------------------

export interface SMSSentEvent {
  type: 'SMS_SENT' | 'SMS_FAILED' | 'SMS_DELIVERED' | 'SMS_BOUNCED';
  payload: SMSMessageResponse;
  gatewayType: SMSGatewayType;
  shopId: string;
  timestamp: Date;
}

// -----------------------------------------------------------------------------
// Internal tracking types
// -----------------------------------------------------------------------------

export interface SMSSendRecord {
  messageId: string;
  shopId: string;
  recipientPhone: string;
  gatewayType: SMSGatewayType;
  externalMessageId?: string;
  status: SMSDeliveryStatus;
  attempts: number;
  lastAttemptAt: Date;
  cost?: number;
}

export interface SMSRetryPolicy {
  maxRetries: number;
  baseDelayMs: number;
  maxDelayMs: number;
  backoffMultiplier: number;
}
